---
title: "Feed efficiency phenotype"
output: html_document
---

##Generate a phylogenetic tree 

```{r, engine='bash'}
#Adjust ID lengths for clearcut command
sed -i -e 's/>/>AAAAAAAAAA/g' usearch_outputs/otus2.align

#Generate a phylip format distance matrix
mothur "#dist.seqs(fasta=usearch_outputs/otus2.align, output=lt, processors=8)"

#Generate a distance-based phylogenetic tree 
mothur "#clearcut(phylip=usearch_outputs/otus2.phylip.dist)"

#Adjust back ID lengths
sed -i -e 's/AAAAAAAAAA//g' usearch_outputs/otus2.phylip.tre
```


```{r, engine='bash'}
#Summary table with samples sequence depth
biom summarize-table -i biom_files/otu_table_final.biom -o biom_files/otu_table_final_summary.txt

#Subsample OTU table to same sequence depth across samples
single_rarefaction.py -i biom_files/otu_table_final.biom -o biom_files/otu_table_final_rarefied.biom -d 10000 

#Create QIIME parameters file
echo 'beta_diversity:metrics weighted_unifrac' > qiime_parameters.txt

#Calculate beta diversity (pairwise sample dissimilarity)
beta_diversity_through_plots.py -i biom_files/otu_table_final_rarefied.biom -o beta_div_full -t usearch_outputs/otus2.phylip.tre -m mapping_files/mapping_file.txt -p qiime_parameters.txt
```

```{r, fig.cap='Hello', fig.height=6, fig.width=6}
library(ggplot2)

data_full <- read.table("beta_div_full/weighted_unifrac_pc.txt", skip = 9, nrows = 247, sep = "\t")
pc_vectors <- data_full[, c("V1", "V2", "V3")]
colnames(pc_vectors) <- c("Sample", "PC1", "PC2")

mapping_file <- read.table("mapping_files/mapping_file.txt")
mapping_subset <- mapping_file[,c("V1","V5")]
colnames(mapping_subset) <- c("Sample", "Sex")

pcoa_data <- merge(pc_vectors, mapping_subset,by="Sample")

pcoa_plot_full <- ggplot(pcoa_data, aes(x=PC1, y=PC2, color=Sex)) + geom_point(size=2.5) + labs(x="PC1 (31.8%)", y="PC2 (16.5%)") + theme(axis.line=element_line(color = "black", size = 1), axis.ticks=element_line(color="black"), axis.text=element_text(color="black", size=12, face="bold"), axis.title=element_text(color="black", size=12, face="bold"), legend.title=element_blank(), legend.text=element_text(color="black", size=10, face="bold"))

pdf("Test.pdf", height = 6, width = 6)
pcoa_plot_full
dev.off()
```